package pp.tanks.model.item;

public enum ItemEnum {
    HEAVY_PROJECTILE, NORMAL_PROJECTILE, LIGHT_PROJECTILE,
    HEAVY_ARMOR, NORMAL_ARMOR, LIGHT_ARMOR,
    HEAVY_TURRET, NORMAL_TURRET, LIGHT_TURRET
}
